version: "3.9"

services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=1
      - MYSQL_DATABASE=triple
      - MYSQL_USER=1
      - MYSQL_PASSWORD=1
    restart: always
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  
  server:
    container_name: server
    image: node:16.13.0
    build: 
      context: ..
      dockerfile: docker/events.Dockerfile
    environment:
      - DB_ADDRESS=mysql://1:1@db:3306/triple
      - SERVER_PORT=8080
      - SERVER_ADDRESS=0.0.0.0
    restart: always
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    ports:
      - 8080:8080